package it.polimi.ingsw.cg_26.model;

public enum StatoAvanzamentoTurno
{
	ATTESA_COMANDO, ATTESA_SETTORE_DESTINAZIONE, ATTESA_CARTA, ATTESA_SETTORE_LUCI, ATTESA_SETTORE_RUMORE, ATTESA_PROPRIO_SETTORE, ATTESA_USA_O_SCARTA, ATTESA_CARTA_DA_SCARTARE;
}
